version: "3.8"

services: 
  nginx-port1:
    image: nginx:latest
    container_name: nginx-port1
    ports: 
      - 8080:80

  nginx-port2:
    image: nginx:latest
    container_name: nginx-port2
    ports:
      - protocol: tcp
        published: 8081
        target: 80
