version: "3.9"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: raplidocker
      MONGO_INITDB_ROOT_PASSWORD: rapli123
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo1:/data/db"
